//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chief.I18N {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chief.I18N.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baozi 包管理器.
        /// </summary>
        internal static string Baozi {
            get {
                return ResourceManager.GetString("Baozi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chief 本体设置.
        /// </summary>
        internal static string ChiefConfig {
            get {
                return ResourceManager.GetString("ChiefConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主题样式.
        /// </summary>
        internal static string ConfigA1 {
            get {
                return ResourceManager.GetString("ConfigA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 语言设置 (Language).
        /// </summary>
        internal static string ConfigA2 {
            get {
                return ResourceManager.GetString("ConfigA2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        internal static string ConfigTitle {
            get {
                return ResourceManager.GetString("ConfigTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全新安装.
        /// </summary>
        internal static string InstallButton {
            get {
                return ResourceManager.GetString("InstallButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JoyEngine 引擎.
        /// </summary>
        internal static string JoyECS {
            get {
                return ResourceManager.GetString("JoyECS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模块设置.
        /// </summary>
        internal static string ModifyButton {
            get {
                return ResourceManager.GetString("ModifyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安装，编辑或卸载此设备上的.
        /// </summary>
        internal static string ModuleManageSubtitle {
            get {
                return ResourceManager.GetString("ModuleManageSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理.
        /// </summary>
        internal static string ModuleManageTitle {
            get {
                return ResourceManager.GetString("ModuleManageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *: 目前，多语言支持仍在测试中，因此翻译会不完善或不准确，建议使用“简体中文”语言。.
        /// </summary>
        internal static string TranslateNotice {
            get {
                return ResourceManager.GetString("TranslateNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 欢迎使用 Chief.
        /// </summary>
        internal static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woolang 编译器.
        /// </summary>
        internal static string Woolang {
            get {
                return ResourceManager.GetString("Woolang", resourceCulture);
            }
        }
    }
}
